// Operational Data Source (ODS) gRPC contract.
//
// The ODS is the low-latency, current-state source of truth. Its schema is
// deliberately DIFFERENT from the canonical BFF domain model: it is
// resource-centric, uses its own enum vocabulary ("state" not "status"),
// carries operational metadata, and exposes a dedicated cheap freshness probe
// so the BFF can make a TTL routing decision WITHOUT paying for a full read.
//
// Traceability: REQ-DS-001, REQ-DS-002, REQ-RT-003, REQ-PERF-002

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: operational/v1/operational.proto

package opsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------------------------
// Source-native enums. NOTE: the vocabulary differs from the canonical model on
// purpose ("PROVISIONING" vs canonical PENDING, etc). Mapping is explicit in
// internal/mapper/operational.go.
// ---------------------------------------------------------------------------
type ResourceState int32

const (
	ResourceState_RESOURCE_STATE_UNSPECIFIED  ResourceState = 0
	ResourceState_RESOURCE_STATE_PROVISIONING ResourceState = 1
	ResourceState_RESOURCE_STATE_ACTIVE       ResourceState = 2
	ResourceState_RESOURCE_STATE_SUSPENDED    ResourceState = 3
	ResourceState_RESOURCE_STATE_DEGRADED     ResourceState = 4
	ResourceState_RESOURCE_STATE_TERMINATING  ResourceState = 5
	ResourceState_RESOURCE_STATE_TERMINATED   ResourceState = 6
	ResourceState_RESOURCE_STATE_ERROR        ResourceState = 7
)

// Enum value maps for ResourceState.
var (
	ResourceState_name = map[int32]string{
		0: "RESOURCE_STATE_UNSPECIFIED",
		1: "RESOURCE_STATE_PROVISIONING",
		2: "RESOURCE_STATE_ACTIVE",
		3: "RESOURCE_STATE_SUSPENDED",
		4: "RESOURCE_STATE_DEGRADED",
		5: "RESOURCE_STATE_TERMINATING",
		6: "RESOURCE_STATE_TERMINATED",
		7: "RESOURCE_STATE_ERROR",
	}
	ResourceState_value = map[string]int32{
		"RESOURCE_STATE_UNSPECIFIED":  0,
		"RESOURCE_STATE_PROVISIONING": 1,
		"RESOURCE_STATE_ACTIVE":       2,
		"RESOURCE_STATE_SUSPENDED":    3,
		"RESOURCE_STATE_DEGRADED":     4,
		"RESOURCE_STATE_TERMINATING":  5,
		"RESOURCE_STATE_TERMINATED":   6,
		"RESOURCE_STATE_ERROR":        7,
	}
)

func (x ResourceState) Enum() *ResourceState {
	p := new(ResourceState)
	*p = x
	return p
}

func (x ResourceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceState) Descriptor() protoreflect.EnumDescriptor {
	return file_operational_v1_operational_proto_enumTypes[0].Descriptor()
}

func (ResourceState) Type() protoreflect.EnumType {
	return &file_operational_v1_operational_proto_enumTypes[0]
}

func (x ResourceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceState.Descriptor instead.
func (ResourceState) EnumDescriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{0}
}

type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_SERVING     HealthState = 1
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 2
	HealthState_HEALTH_STATE_NOT_SERVING HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_SERVING",
		2: "HEALTH_STATE_DEGRADED",
		3: "HEALTH_STATE_NOT_SERVING",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_SERVING":     1,
		"HEALTH_STATE_DEGRADED":    2,
		"HEALTH_STATE_NOT_SERVING": 3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_operational_v1_operational_proto_enumTypes[1].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_operational_v1_operational_proto_enumTypes[1]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{1}
}

// Every read carries tenant context; the source enforces isolation itself and
// the BFF never relies on that alone (defence in depth, REQ-SEC-004).
type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Principal     string                 `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_operational_v1_operational_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RequestContext) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

type FreshnessEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wall-clock time at which the source last refreshed this record.
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Server time at response generation, used by the BFF for clock-skew
	// correction (REQ-EDGE-010).
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Source-declared confidence that the record reflects reality.
	RefreshSource string `protobuf:"bytes,3,opt,name=refresh_source,json=refreshSource,proto3" json:"refresh_source,omitempty"` // e.g. "poller", "event-stream", "reconciler"
	// Monotonic version of the record; used for conflict detection.
	Version       uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreshnessEnvelope) Reset() {
	*x = FreshnessEnvelope{}
	mi := &file_operational_v1_operational_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreshnessEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreshnessEnvelope) ProtoMessage() {}

func (x *FreshnessEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreshnessEnvelope.ProtoReflect.Descriptor instead.
func (*FreshnessEnvelope) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{1}
}

func (x *FreshnessEnvelope) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *FreshnessEnvelope) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *FreshnessEnvelope) GetRefreshSource() string {
	if x != nil {
		return x.RefreshSource
	}
	return ""
}

func (x *FreshnessEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetResourceFreshnessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceFreshnessRequest) Reset() {
	*x = GetResourceFreshnessRequest{}
	mi := &file_operational_v1_operational_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceFreshnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceFreshnessRequest) ProtoMessage() {}

func (x *GetResourceFreshnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceFreshnessRequest.ProtoReflect.Descriptor instead.
func (*GetResourceFreshnessRequest) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceFreshnessRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetResourceFreshnessRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetResourceFreshnessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Freshness     *FreshnessEnvelope     `protobuf:"bytes,3,opt,name=freshness,proto3" json:"freshness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceFreshnessResponse) Reset() {
	*x = GetResourceFreshnessResponse{}
	mi := &file_operational_v1_operational_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceFreshnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceFreshnessResponse) ProtoMessage() {}

func (x *GetResourceFreshnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceFreshnessResponse.ProtoReflect.Descriptor instead.
func (*GetResourceFreshnessResponse) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourceFreshnessResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetResourceFreshnessResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResourceFreshnessResponse) GetFreshness() *FreshnessEnvelope {
	if x != nil {
		return x.Freshness
	}
	return nil
}

type GetResourceRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Context    *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ResourceId string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Optional projection; empty means "all".
	FieldMask     []string `protobuf:"bytes,3,rep,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_operational_v1_operational_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{4}
}

func (x *GetResourceRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetResourceRequest) GetFieldMask() []string {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *OperationalResource   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_operational_v1_operational_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{5}
}

func (x *GetResourceResponse) GetResource() *OperationalResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetResourceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceStateRequest) Reset() {
	*x = GetResourceStateRequest{}
	mi := &file_operational_v1_operational_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceStateRequest) ProtoMessage() {}

func (x *GetResourceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceStateRequest.ProtoReflect.Descriptor instead.
func (*GetResourceStateRequest) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{6}
}

func (x *GetResourceStateRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetResourceStateRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetResourceStateResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ResourceId string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	State      ResourceState          `protobuf:"varint,2,opt,name=state,proto3,enum=operational.v1.ResourceState" json:"state,omitempty"`
	Substate   string                 `protobuf:"bytes,3,opt,name=substate,proto3" json:"substate,omitempty"`
	Freshness  *FreshnessEnvelope     `protobuf:"bytes,4,opt,name=freshness,proto3" json:"freshness,omitempty"`
	// Carried on the narrow read as well as the full one. Without it the BFF
	// cannot tell, from a cheap status read, that a workflow is mutating the
	// resource -- and the "a running execution may override operational state"
	// precedence rule could only ever fire on the expensive both-source
	// endpoints, leaving /status and /details disagreeing (REQ-PREC-003).
	InFlightExecutionRef string `protobuf:"bytes,5,opt,name=in_flight_execution_ref,json=inFlightExecutionRef,proto3" json:"in_flight_execution_ref,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetResourceStateResponse) Reset() {
	*x = GetResourceStateResponse{}
	mi := &file_operational_v1_operational_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceStateResponse) ProtoMessage() {}

func (x *GetResourceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceStateResponse.ProtoReflect.Descriptor instead.
func (*GetResourceStateResponse) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{7}
}

func (x *GetResourceStateResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetResourceStateResponse) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *GetResourceStateResponse) GetSubstate() string {
	if x != nil {
		return x.Substate
	}
	return ""
}

func (x *GetResourceStateResponse) GetFreshness() *FreshnessEnvelope {
	if x != nil {
		return x.Freshness
	}
	return nil
}

func (x *GetResourceStateResponse) GetInFlightExecutionRef() string {
	if x != nil {
		return x.InFlightExecutionRef
	}
	return ""
}

type BatchGetResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResourcesRequest) Reset() {
	*x = BatchGetResourcesRequest{}
	mi := &file_operational_v1_operational_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResourcesRequest) ProtoMessage() {}

func (x *BatchGetResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResourcesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetResourcesRequest) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetResourcesRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BatchGetResourcesRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type BatchGetResourcesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Resources          []*OperationalResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	MissingResourceIds []string               `protobuf:"bytes,2,rep,name=missing_resource_ids,json=missingResourceIds,proto3" json:"missing_resource_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchGetResourcesResponse) Reset() {
	*x = BatchGetResourcesResponse{}
	mi := &file_operational_v1_operational_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResourcesResponse) ProtoMessage() {}

func (x *BatchGetResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResourcesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResourcesResponse) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetResourcesResponse) GetResources() []*OperationalResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *BatchGetResourcesResponse) GetMissingResourceIds() []string {
	if x != nil {
		return x.MissingResourceIds
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_operational_v1_operational_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         HealthState            `protobuf:"varint,1,opt,name=state,proto3,enum=operational.v1.HealthState" json:"state,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_operational_v1_operational_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetState() HealthState {
	if x != nil {
		return x.State
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// The operational record. Field names intentionally do NOT match the canonical
// model (customer_ref vs customerId, state vs status, ...).
type OperationalResource struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResourceId          string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CustomerRef         string                 `protobuf:"bytes,2,opt,name=customer_ref,json=customerRef,proto3" json:"customer_ref,omitempty"`
	TenantId            string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResourceType        string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	State               ResourceState          `protobuf:"varint,5,opt,name=state,proto3,enum=operational.v1.ResourceState" json:"state,omitempty"`
	Substate            string                 `protobuf:"bytes,6,opt,name=substate,proto3" json:"substate,omitempty"`
	Ownership           *OwnershipRecord       `protobuf:"bytes,7,opt,name=ownership,proto3" json:"ownership,omitempty"`
	Configuration       map[string]string      `protobuf:"bytes,8,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics             []*MetricSample        `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Topology            *TopologyRecord        `protobuf:"bytes,10,opt,name=topology,proto3" json:"topology,omitempty"`
	OperationalMetadata map[string]string      `protobuf:"bytes,11,rep,name=operational_metadata,json=operationalMetadata,proto3" json:"operational_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels              map[string]string      `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Freshness           *FreshnessEnvelope     `protobuf:"bytes,13,opt,name=freshness,proto3" json:"freshness,omitempty"`
	// Set when the ODS itself knows an execution is mutating this resource.
	// Used by SourcePrecedencePolicy (REQ-PREC-003).
	InFlightExecutionRef string `protobuf:"bytes,14,opt,name=in_flight_execution_ref,json=inFlightExecutionRef,proto3" json:"in_flight_execution_ref,omitempty"`
	// Schema contract version emitted by the source (REQ-EDGE-017).
	SchemaVersion string `protobuf:"bytes,15,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationalResource) Reset() {
	*x = OperationalResource{}
	mi := &file_operational_v1_operational_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationalResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationalResource) ProtoMessage() {}

func (x *OperationalResource) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationalResource.ProtoReflect.Descriptor instead.
func (*OperationalResource) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{12}
}

func (x *OperationalResource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *OperationalResource) GetCustomerRef() string {
	if x != nil {
		return x.CustomerRef
	}
	return ""
}

func (x *OperationalResource) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OperationalResource) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *OperationalResource) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *OperationalResource) GetSubstate() string {
	if x != nil {
		return x.Substate
	}
	return ""
}

func (x *OperationalResource) GetOwnership() *OwnershipRecord {
	if x != nil {
		return x.Ownership
	}
	return nil
}

func (x *OperationalResource) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *OperationalResource) GetMetrics() []*MetricSample {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *OperationalResource) GetTopology() *TopologyRecord {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *OperationalResource) GetOperationalMetadata() map[string]string {
	if x != nil {
		return x.OperationalMetadata
	}
	return nil
}

func (x *OperationalResource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *OperationalResource) GetFreshness() *FreshnessEnvelope {
	if x != nil {
		return x.Freshness
	}
	return nil
}

func (x *OperationalResource) GetInFlightExecutionRef() string {
	if x != nil {
		return x.InFlightExecutionRef
	}
	return ""
}

func (x *OperationalResource) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type OwnershipRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"` // "team" | "user" | "service"
	OwnerEmail    string                 `protobuf:"bytes,3,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	CostCentre    string                 `protobuf:"bytes,4,opt,name=cost_centre,json=costCentre,proto3" json:"cost_centre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnershipRecord) Reset() {
	*x = OwnershipRecord{}
	mi := &file_operational_v1_operational_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipRecord) ProtoMessage() {}

func (x *OwnershipRecord) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipRecord.ProtoReflect.Descriptor instead.
func (*OwnershipRecord) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{13}
}

func (x *OwnershipRecord) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *OwnershipRecord) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *OwnershipRecord) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *OwnershipRecord) GetCostCentre() string {
	if x != nil {
		return x.CostCentre
	}
	return ""
}

type MetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	SampledAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_operational_v1_operational_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{14}
}

func (x *MetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricSample) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricSample) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

type TopologyRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Region         string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Zone           string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Cluster        string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	UpstreamRefs   []string               `protobuf:"bytes,4,rep,name=upstream_refs,json=upstreamRefs,proto3" json:"upstream_refs,omitempty"`
	DownstreamRefs []string               `protobuf:"bytes,5,rep,name=downstream_refs,json=downstreamRefs,proto3" json:"downstream_refs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopologyRecord) Reset() {
	*x = TopologyRecord{}
	mi := &file_operational_v1_operational_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRecord) ProtoMessage() {}

func (x *TopologyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_operational_v1_operational_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRecord.ProtoReflect.Descriptor instead.
func (*TopologyRecord) Descriptor() ([]byte, []int) {
	return file_operational_v1_operational_proto_rawDescGZIP(), []int{15}
}

func (x *TopologyRecord) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *TopologyRecord) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *TopologyRecord) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *TopologyRecord) GetUpstreamRefs() []string {
	if x != nil {
		return x.UpstreamRefs
	}
	return nil
}

func (x *TopologyRecord) GetDownstreamRefs() []string {
	if x != nil {
		return x.DownstreamRefs
	}
	return nil
}

var File_operational_v1_operational_proto protoreflect.FileDescriptor

const file_operational_v1_operational_proto_rawDesc = "" +
	"\n" +
	" operational/v1/operational.proto\x12\x0eoperational.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"r\n" +
	"\x0eRequestContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x1c\n" +
	"\tprincipal\x18\x03 \x01(\tR\tprincipal\"\xd0\x01\n" +
	"\x11FreshnessEnvelope\x12=\n" +
	"\flast_updated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12%\n" +
	"\x0erefresh_source\x18\x03 \x01(\tR\rrefreshSource\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\"x\n" +
	"\x1bGetResourceFreshnessRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.operational.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"\x96\x01\n" +
	"\x1cGetResourceFreshnessResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12?\n" +
	"\tfreshness\x18\x03 \x01(\v2!.operational.v1.FreshnessEnvelopeR\tfreshness\"\x8e\x01\n" +
	"\x12GetResourceRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.operational.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x03 \x03(\tR\tfieldMask\"V\n" +
	"\x13GetResourceResponse\x12?\n" +
	"\bresource\x18\x01 \x01(\v2#.operational.v1.OperationalResourceR\bresource\"t\n" +
	"\x17GetResourceStateRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.operational.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"\x84\x02\n" +
	"\x18GetResourceStateResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.operational.v1.ResourceStateR\x05state\x12\x1a\n" +
	"\bsubstate\x18\x03 \x01(\tR\bsubstate\x12?\n" +
	"\tfreshness\x18\x04 \x01(\v2!.operational.v1.FreshnessEnvelopeR\tfreshness\x125\n" +
	"\x17in_flight_execution_ref\x18\x05 \x01(\tR\x14inFlightExecutionRef\"w\n" +
	"\x18BatchGetResourcesRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.operational.v1.RequestContextR\acontext\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\"\x90\x01\n" +
	"\x19BatchGetResourcesResponse\x12A\n" +
	"\tresources\x18\x01 \x03(\v2#.operational.v1.OperationalResourceR\tresources\x120\n" +
	"\x14missing_resource_ids\x18\x02 \x03(\tR\x12missingResourceIds\"\x0f\n" +
	"\rHealthRequest\"[\n" +
	"\x0eHealthResponse\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.operational.v1.HealthStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x9b\b\n" +
	"\x13OperationalResource\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcustomer_ref\x18\x02 \x01(\tR\vcustomerRef\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x123\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1d.operational.v1.ResourceStateR\x05state\x12\x1a\n" +
	"\bsubstate\x18\x06 \x01(\tR\bsubstate\x12=\n" +
	"\townership\x18\a \x01(\v2\x1f.operational.v1.OwnershipRecordR\townership\x12\\\n" +
	"\rconfiguration\x18\b \x03(\v26.operational.v1.OperationalResource.ConfigurationEntryR\rconfiguration\x126\n" +
	"\ametrics\x18\t \x03(\v2\x1c.operational.v1.MetricSampleR\ametrics\x12:\n" +
	"\btopology\x18\n" +
	" \x01(\v2\x1e.operational.v1.TopologyRecordR\btopology\x12o\n" +
	"\x14operational_metadata\x18\v \x03(\v2<.operational.v1.OperationalResource.OperationalMetadataEntryR\x13operationalMetadata\x12G\n" +
	"\x06labels\x18\f \x03(\v2/.operational.v1.OperationalResource.LabelsEntryR\x06labels\x12?\n" +
	"\tfreshness\x18\r \x01(\v2!.operational.v1.FreshnessEnvelopeR\tfreshness\x125\n" +
	"\x17in_flight_execution_ref\x18\x0e \x01(\tR\x14inFlightExecutionRef\x12%\n" +
	"\x0eschema_version\x18\x0f \x01(\tR\rschemaVersion\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aF\n" +
	"\x18OperationalMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0fOwnershipRecord\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\x12\x1f\n" +
	"\vowner_email\x18\x03 \x01(\tR\n" +
	"ownerEmail\x12\x1f\n" +
	"\vcost_centre\x18\x04 \x01(\tR\n" +
	"costCentre\"\x87\x01\n" +
	"\fMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x129\n" +
	"\n" +
	"sampled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\"\xa4\x01\n" +
	"\x0eTopologyRecord\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12#\n" +
	"\rupstream_refs\x18\x04 \x03(\tR\fupstreamRefs\x12'\n" +
	"\x0fdownstream_refs\x18\x05 \x03(\tR\x0edownstreamRefs*\xff\x01\n" +
	"\rResourceState\x12\x1e\n" +
	"\x1aRESOURCE_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRESOURCE_STATE_PROVISIONING\x10\x01\x12\x19\n" +
	"\x15RESOURCE_STATE_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18RESOURCE_STATE_SUSPENDED\x10\x03\x12\x1b\n" +
	"\x17RESOURCE_STATE_DEGRADED\x10\x04\x12\x1e\n" +
	"\x1aRESOURCE_STATE_TERMINATING\x10\x05\x12\x1d\n" +
	"\x19RESOURCE_STATE_TERMINATED\x10\x06\x12\x18\n" +
	"\x14RESOURCE_STATE_ERROR\x10\a*~\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_SERVING\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x02\x12\x1c\n" +
	"\x18HEALTH_STATE_NOT_SERVING\x10\x032\xf9\x03\n" +
	"\x12OperationalService\x12q\n" +
	"\x14GetResourceFreshness\x12+.operational.v1.GetResourceFreshnessRequest\x1a,.operational.v1.GetResourceFreshnessResponse\x12V\n" +
	"\vGetResource\x12\".operational.v1.GetResourceRequest\x1a#.operational.v1.GetResourceResponse\x12e\n" +
	"\x10GetResourceState\x12'.operational.v1.GetResourceStateRequest\x1a(.operational.v1.GetResourceStateResponse\x12h\n" +
	"\x11BatchGetResources\x12(.operational.v1.BatchGetResourcesRequest\x1a).operational.v1.BatchGetResourcesResponse\x12G\n" +
	"\x06Health\x12\x1d.operational.v1.HealthRequest\x1a\x1e.operational.v1.HealthResponseBRZPgithub.com/udaykishore/ttl-aware-bff/internal/datasource/operational/opsv1;opsv1b\x06proto3"

var (
	file_operational_v1_operational_proto_rawDescOnce sync.Once
	file_operational_v1_operational_proto_rawDescData []byte
)

func file_operational_v1_operational_proto_rawDescGZIP() []byte {
	file_operational_v1_operational_proto_rawDescOnce.Do(func() {
		file_operational_v1_operational_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operational_v1_operational_proto_rawDesc), len(file_operational_v1_operational_proto_rawDesc)))
	})
	return file_operational_v1_operational_proto_rawDescData
}

var file_operational_v1_operational_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_operational_v1_operational_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_operational_v1_operational_proto_goTypes = []any{
	(ResourceState)(0),                   // 0: operational.v1.ResourceState
	(HealthState)(0),                     // 1: operational.v1.HealthState
	(*RequestContext)(nil),               // 2: operational.v1.RequestContext
	(*FreshnessEnvelope)(nil),            // 3: operational.v1.FreshnessEnvelope
	(*GetResourceFreshnessRequest)(nil),  // 4: operational.v1.GetResourceFreshnessRequest
	(*GetResourceFreshnessResponse)(nil), // 5: operational.v1.GetResourceFreshnessResponse
	(*GetResourceRequest)(nil),           // 6: operational.v1.GetResourceRequest
	(*GetResourceResponse)(nil),          // 7: operational.v1.GetResourceResponse
	(*GetResourceStateRequest)(nil),      // 8: operational.v1.GetResourceStateRequest
	(*GetResourceStateResponse)(nil),     // 9: operational.v1.GetResourceStateResponse
	(*BatchGetResourcesRequest)(nil),     // 10: operational.v1.BatchGetResourcesRequest
	(*BatchGetResourcesResponse)(nil),    // 11: operational.v1.BatchGetResourcesResponse
	(*HealthRequest)(nil),                // 12: operational.v1.HealthRequest
	(*HealthResponse)(nil),               // 13: operational.v1.HealthResponse
	(*OperationalResource)(nil),          // 14: operational.v1.OperationalResource
	(*OwnershipRecord)(nil),              // 15: operational.v1.OwnershipRecord
	(*MetricSample)(nil),                 // 16: operational.v1.MetricSample
	(*TopologyRecord)(nil),               // 17: operational.v1.TopologyRecord
	nil,                                  // 18: operational.v1.OperationalResource.ConfigurationEntry
	nil,                                  // 19: operational.v1.OperationalResource.OperationalMetadataEntry
	nil,                                  // 20: operational.v1.OperationalResource.LabelsEntry
	(*timestamppb.Timestamp)(nil),        // 21: google.protobuf.Timestamp
}
var file_operational_v1_operational_proto_depIdxs = []int32{
	21, // 0: operational.v1.FreshnessEnvelope.last_updated:type_name -> google.protobuf.Timestamp
	21, // 1: operational.v1.FreshnessEnvelope.server_time:type_name -> google.protobuf.Timestamp
	2,  // 2: operational.v1.GetResourceFreshnessRequest.context:type_name -> operational.v1.RequestContext
	3,  // 3: operational.v1.GetResourceFreshnessResponse.freshness:type_name -> operational.v1.FreshnessEnvelope
	2,  // 4: operational.v1.GetResourceRequest.context:type_name -> operational.v1.RequestContext
	14, // 5: operational.v1.GetResourceResponse.resource:type_name -> operational.v1.OperationalResource
	2,  // 6: operational.v1.GetResourceStateRequest.context:type_name -> operational.v1.RequestContext
	0,  // 7: operational.v1.GetResourceStateResponse.state:type_name -> operational.v1.ResourceState
	3,  // 8: operational.v1.GetResourceStateResponse.freshness:type_name -> operational.v1.FreshnessEnvelope
	2,  // 9: operational.v1.BatchGetResourcesRequest.context:type_name -> operational.v1.RequestContext
	14, // 10: operational.v1.BatchGetResourcesResponse.resources:type_name -> operational.v1.OperationalResource
	1,  // 11: operational.v1.HealthResponse.state:type_name -> operational.v1.HealthState
	0,  // 12: operational.v1.OperationalResource.state:type_name -> operational.v1.ResourceState
	15, // 13: operational.v1.OperationalResource.ownership:type_name -> operational.v1.OwnershipRecord
	18, // 14: operational.v1.OperationalResource.configuration:type_name -> operational.v1.OperationalResource.ConfigurationEntry
	16, // 15: operational.v1.OperationalResource.metrics:type_name -> operational.v1.MetricSample
	17, // 16: operational.v1.OperationalResource.topology:type_name -> operational.v1.TopologyRecord
	19, // 17: operational.v1.OperationalResource.operational_metadata:type_name -> operational.v1.OperationalResource.OperationalMetadataEntry
	20, // 18: operational.v1.OperationalResource.labels:type_name -> operational.v1.OperationalResource.LabelsEntry
	3,  // 19: operational.v1.OperationalResource.freshness:type_name -> operational.v1.FreshnessEnvelope
	21, // 20: operational.v1.MetricSample.sampled_at:type_name -> google.protobuf.Timestamp
	4,  // 21: operational.v1.OperationalService.GetResourceFreshness:input_type -> operational.v1.GetResourceFreshnessRequest
	6,  // 22: operational.v1.OperationalService.GetResource:input_type -> operational.v1.GetResourceRequest
	8,  // 23: operational.v1.OperationalService.GetResourceState:input_type -> operational.v1.GetResourceStateRequest
	10, // 24: operational.v1.OperationalService.BatchGetResources:input_type -> operational.v1.BatchGetResourcesRequest
	12, // 25: operational.v1.OperationalService.Health:input_type -> operational.v1.HealthRequest
	5,  // 26: operational.v1.OperationalService.GetResourceFreshness:output_type -> operational.v1.GetResourceFreshnessResponse
	7,  // 27: operational.v1.OperationalService.GetResource:output_type -> operational.v1.GetResourceResponse
	9,  // 28: operational.v1.OperationalService.GetResourceState:output_type -> operational.v1.GetResourceStateResponse
	11, // 29: operational.v1.OperationalService.BatchGetResources:output_type -> operational.v1.BatchGetResourcesResponse
	13, // 30: operational.v1.OperationalService.Health:output_type -> operational.v1.HealthResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_operational_v1_operational_proto_init() }
func file_operational_v1_operational_proto_init() {
	if File_operational_v1_operational_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operational_v1_operational_proto_rawDesc), len(file_operational_v1_operational_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operational_v1_operational_proto_goTypes,
		DependencyIndexes: file_operational_v1_operational_proto_depIdxs,
		EnumInfos:         file_operational_v1_operational_proto_enumTypes,
		MessageInfos:      file_operational_v1_operational_proto_msgTypes,
	}.Build()
	File_operational_v1_operational_proto = out.File
	file_operational_v1_operational_proto_goTypes = nil
	file_operational_v1_operational_proto_depIdxs = nil
}
