// Operational Data Source (ODS) gRPC contract.
//
// The ODS is the low-latency, current-state source of truth. Its schema is
// deliberately DIFFERENT from the canonical BFF domain model: it is
// resource-centric, uses its own enum vocabulary ("state" not "status"),
// carries operational metadata, and exposes a dedicated cheap freshness probe
// so the BFF can make a TTL routing decision WITHOUT paying for a full read.
//
// Traceability: REQ-DS-001, REQ-DS-002, REQ-RT-003, REQ-PERF-002

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: operational/v1/operational.proto

package opsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationalService_GetResourceFreshness_FullMethodName = "/operational.v1.OperationalService/GetResourceFreshness"
	OperationalService_GetResource_FullMethodName          = "/operational.v1.OperationalService/GetResource"
	OperationalService_GetResourceState_FullMethodName     = "/operational.v1.OperationalService/GetResourceState"
	OperationalService_BatchGetResources_FullMethodName    = "/operational.v1.OperationalService/BatchGetResources"
	OperationalService_Health_FullMethodName               = "/operational.v1.OperationalService/Health"
)

// OperationalServiceClient is the client API for OperationalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationalServiceClient interface {
	// Cheap probe: returns ONLY the freshness envelope for a resource.
	// Used by the BFF TTL/Freshness Manager to route before fetching.
	GetResourceFreshness(ctx context.Context, in *GetResourceFreshnessRequest, opts ...grpc.CallOption) (*GetResourceFreshnessResponse, error)
	// Full current-state read.
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error)
	// Narrow read used by the /status endpoint.
	GetResourceState(ctx context.Context, in *GetResourceStateRequest, opts ...grpc.CallOption) (*GetResourceStateResponse, error)
	// Batch read (connection reuse / fan-in optimisation).
	BatchGetResources(ctx context.Context, in *BatchGetResourcesRequest, opts ...grpc.CallOption) (*BatchGetResourcesResponse, error)
	// Liveness/health of the source itself.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type operationalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationalServiceClient(cc grpc.ClientConnInterface) OperationalServiceClient {
	return &operationalServiceClient{cc}
}

func (c *operationalServiceClient) GetResourceFreshness(ctx context.Context, in *GetResourceFreshnessRequest, opts ...grpc.CallOption) (*GetResourceFreshnessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceFreshnessResponse)
	err := c.cc.Invoke(ctx, OperationalService_GetResourceFreshness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationalServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceResponse)
	err := c.cc.Invoke(ctx, OperationalService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationalServiceClient) GetResourceState(ctx context.Context, in *GetResourceStateRequest, opts ...grpc.CallOption) (*GetResourceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceStateResponse)
	err := c.cc.Invoke(ctx, OperationalService_GetResourceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationalServiceClient) BatchGetResources(ctx context.Context, in *BatchGetResourcesRequest, opts ...grpc.CallOption) (*BatchGetResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetResourcesResponse)
	err := c.cc.Invoke(ctx, OperationalService_BatchGetResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationalServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, OperationalService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationalServiceServer is the server API for OperationalService service.
// All implementations must embed UnimplementedOperationalServiceServer
// for forward compatibility.
type OperationalServiceServer interface {
	// Cheap probe: returns ONLY the freshness envelope for a resource.
	// Used by the BFF TTL/Freshness Manager to route before fetching.
	GetResourceFreshness(context.Context, *GetResourceFreshnessRequest) (*GetResourceFreshnessResponse, error)
	// Full current-state read.
	GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error)
	// Narrow read used by the /status endpoint.
	GetResourceState(context.Context, *GetResourceStateRequest) (*GetResourceStateResponse, error)
	// Batch read (connection reuse / fan-in optimisation).
	BatchGetResources(context.Context, *BatchGetResourcesRequest) (*BatchGetResourcesResponse, error)
	// Liveness/health of the source itself.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedOperationalServiceServer()
}

// UnimplementedOperationalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationalServiceServer struct{}

func (UnimplementedOperationalServiceServer) GetResourceFreshness(context.Context, *GetResourceFreshnessRequest) (*GetResourceFreshnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceFreshness not implemented")
}
func (UnimplementedOperationalServiceServer) GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedOperationalServiceServer) GetResourceState(context.Context, *GetResourceStateRequest) (*GetResourceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceState not implemented")
}
func (UnimplementedOperationalServiceServer) BatchGetResources(context.Context, *BatchGetResourcesRequest) (*BatchGetResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetResources not implemented")
}
func (UnimplementedOperationalServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedOperationalServiceServer) mustEmbedUnimplementedOperationalServiceServer() {}
func (UnimplementedOperationalServiceServer) testEmbeddedByValue()                            {}

// UnsafeOperationalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationalServiceServer will
// result in compilation errors.
type UnsafeOperationalServiceServer interface {
	mustEmbedUnimplementedOperationalServiceServer()
}

func RegisterOperationalServiceServer(s grpc.ServiceRegistrar, srv OperationalServiceServer) {
	// If the following call pancis, it indicates UnimplementedOperationalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationalService_ServiceDesc, srv)
}

func _OperationalService_GetResourceFreshness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceFreshnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationalServiceServer).GetResourceFreshness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationalService_GetResourceFreshness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationalServiceServer).GetResourceFreshness(ctx, req.(*GetResourceFreshnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationalService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationalServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationalService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationalServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationalService_GetResourceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationalServiceServer).GetResourceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationalService_GetResourceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationalServiceServer).GetResourceState(ctx, req.(*GetResourceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationalService_BatchGetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationalServiceServer).BatchGetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationalService_BatchGetResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationalServiceServer).BatchGetResources(ctx, req.(*BatchGetResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationalService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationalServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationalService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationalServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationalService_ServiceDesc is the grpc.ServiceDesc for OperationalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operational.v1.OperationalService",
	HandlerType: (*OperationalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResourceFreshness",
			Handler:    _OperationalService_GetResourceFreshness_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _OperationalService_GetResource_Handler,
		},
		{
			MethodName: "GetResourceState",
			Handler:    _OperationalService_GetResourceState_Handler,
		},
		{
			MethodName: "BatchGetResources",
			Handler:    _OperationalService_BatchGetResources_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _OperationalService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operational/v1/operational.proto",
}
